drop database if exists homework;

create database Homework;
use Homework;

CREATE TABLE COURSES(
   CCODE varchar (5) primary key ,
   NAME varchar(30),
   DURATION INT CHECK (DURATION >=0),
   FEE INT CHECK (FEE >=0),
   PREREQUISITE varchar(100)
);

INSERT INTO COURSES( CCODE , NAME , DURATION , FEE ,  PREREQUISITE)
VALUES ('C101' , 'Sql' , 54 , 2000, 'Data base');

CREATE TABLE Faculty(
   FACCODE varchar(5) primary key,
   Name varchar(30),
   qual varchar(30),
   Exp varchar (100)
); 

INSERT INTO Faculty( FACCODE,NAME,QUAL,EXP)
VALUES('FAC01','Sriya','PhD','15');

CREATE TABLE COURSE_FACULTY (
    FACCODE VARCHAR(10),
    CCODE VARCHAR (10),
    GRADE CHAR(1),
    PRIMARY KEY (FACCODE, CCODE),
    FOREIGN KEY (FACCODE) REFERENCES FACULTY(FACCODE),
    FOREIGN KEY (CCODE) REFERENCES COURSES(CCODE),
    CHECK (GRADE IN ('A', 'B', 'C'))
);

INSERT INTO COURSE_FACULTY (FACCODE, CCODE, GRADE)
VALUES ('FAC001', 'COURSE001', 'A');

CREATE TABLE BATCHES(
   BCODE VARCHAR(10) primary KEY,
   CCODE VARCHAR(10) REFERENCES COURSES (CCODE),
   FACCODE VARCHAR(10) REFERENCES FACULTY (FACCODE),
   STDATE DATE,
   ENDDATE DATE,
   TIMING INT CHECK (TIMING IN (1,2,3))
);

INSERT INTO BATCHES (BCODE,CCODE,FACCODE,STDATE,ENDDATE,TIMING)
VALUES ('BATCH001','COURSE001','FAC001','2023-09-20',NULL,1);
